sudo: required
services:
 - docker

before_install:
 - docker build -t khanahmad1314/dockersetup -f Dockerfile.dev .

script:
 - docker run khanahmad1314/dockersetup npm run test -- --coverage